# Generated by Django 4.0 on 2024-03-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_foodtype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishe',
            name='image_url',
            field=models.ImageField(null=True, upload_to='static/dishes-image'),
        ),
        migrations.AlterField(
            model_name='dishe',
            name='item_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dishe',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
